<?php

return [
    'brand' => [
        'name'        => 'xpsystems',
        'tagline'     => 'German Web-Provider',
        'description' => 'European infrastructure, digital sovereignty, and developer-first tooling — built and operated from Germany.',
        'domains'     => ['xpsystems.eu', 'xpsystems.de'],
        'version'     => '3.3.1',
    ],
    'nav' => [
        ['label' => 'Services', 'href' => '#services', 'external' => false],
        ['label' => 'Team',     'href' => '#team',     'external' => false],
        //['label' => 'Domains',  'href' => '#domains',  'external' => false],
        ['label' => 'Status',   'href' => 'https://status.xpsystems.eu', 'external' => true],
        ['label' => 'GitHub',   'href' => 'https://github.com/xpsystems', 'external' => true],
    ],
    'hero_ctas' => [
        [
            'label'   => 'GitHub',
            'href'    => 'https://github.com/xpsystems',
            'primary' => false,
        ],
        [
            'label'   => 'System Status',
            'href'    => 'https://status.xpsystems.eu',
            'primary' => true,
        ],
    ],
    'services' => [
        [
            'name'    => 'EuropeHost.eu',
            'type'    => 'service',
            'url'     => 'https://europehost.eu',
            'tagline' => 'European hosting infrastructure',
            'links'   => [
                ['label' => 'eudomains.eu',  'href' => 'https://eudomains.eu'],
                ['label' => 'eushare.eu',    'href' => 'https://eushare.eu'],
                ['label' => 'dsc.pics',      'href' => 'https://dsc.pics'],
                ['label' => 'swiftshare.eu', 'href' => 'https://swiftshare.eu'],
            ],
        ],
        [
            'name'    => 'eu-data.org',
            'type'    => 'service',
            'url'     => 'https://eu-data.org',
            'tagline' => 'European Digital Sovereignty — GDPR-compliant alternatives',
            'links'   => [
                ['label' => 'mail-free.eu',  'href' => 'https://mail-free.eu'],
                ['label' => 'eu-search.org', 'href' => 'https://eu-search.org'],
            ],
        ],
        [
            'name'    => 'MTEX.dev',
            'type'    => 'partner',
            'url'     => 'https://mtex.dev',
            'tagline' => 'Building the tools we actually want to use',
            'links'   => [
                ['label' => 'getmy.name',      'href' => 'https://getmy.name'],
                ['label' => 'status.mtex.dev', 'href' => 'https://status.mtex.dev'],
            ],
        ],
        [
            'name'    => 'api-sandbox.de',
            'type'    => 'service',
            'url'     => 'https://api-sandbox.de',
            'tagline' => 'API development sandbox',
            'links'   => [],
        ],
        [
            'name'    => 'xpsys.eu',
            'type'    => 'service',
            'url'     => 'https://xpsys.eu',
            'tagline' => 'Gateway for services & templates',
            'links'   => [],
        ],
    ],
    'team' => [
        [
            'name'    => 'Fabian Ternis',
            'role'    => 'Founder / Web Dev',
            'url'     => 'https://fabianternis.dev',
            'img_url' => 'https://github.com/michaelninder.png',
        ],
        [
            'name'    => 'Ramsay Brewer',
            'role'    => 'Developer',
            'url'     => 'https://dogwaterdev.de',
            'img_url' => 'https://github.com/dogwaterdev.png',
        ],
    ],
    'stats' => [
        [
            'value'      => '100+',
            'label'      => 'Domains Managed',
            'url'        => 'https://domainlist.fabianternis.de',
            'link_label' => 'View domain list',
        ],
        [
            'value'      => 'Live',
            'label'      => 'Infrastructure Monitored',
            'url'        => 'https://status.xpsystems.eu',
            'link_label' => 'View system status',
        ],
        [
            'value'      => 'Open',
            'label'      => 'Source Projects',
            'url'        => 'https://github.com/xpsystems',
            'link_label' => 'Browse on GitHub',
        ],
    ],
    'footer_links' => [
        ['label' => 'GitHub',      'href' => 'https://github.com/xpsystems/landingpage'],
        ['label' => 'Status',      'href' => 'https://status.xpsystems.eu'],
        ['label' => 'EuropeHost',  'href' => 'https://europehost.eu'],
        ['label' => 'eu-data.org', 'href' => 'https://eu-data.org'],
        ['label' => 'MTEX.dev',    'href' => 'https://mtex.dev'],
    ],
    'status_check_url' => 'https://status.xpsystems.eu/api/status',
    'copyright_year'   => (int) date('Y'),

    /* ── Domain portfolio ─────────────────────────────────────────
     * Each group has: title, (optional) accent colour, and a list
     * of domain entries.  Each entry has: domain, href (null =
     * not linkable), badge (optional label), legacy (bool).
     * -----------------------------------------------------------*/
    /* ── Domain portfolio ─────────────────────────────────────────
     * Each group: title, accent ('accent'|'partner'), optional
     * legacy:true flag.  Each entry: domain, optional badge label.
     * href is always computed as "https://" . $domain in the view.
     * -----------------------------------------------------------*/
    'domain_groups' => [
        [
            'title'   => 'Personal & Identity',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'fternis.de'],
                ['domain' => 'fabianternis.dev'],
                ['domain' => 'fabianternis.de'],
                ['domain' => 'fabian-ternis.de'],
                ['domain' => 'ternis.eu'],
                ['domain' => 'ivoternis.de'],
                ['domain' => 'mysocials.me'],
                ['domain' => 'getsocials.link'],
                ['domain' => 'linkmy.name'],
                ['domain' => 'pleasehireme.eu'],
            ],
        ],
        [
            'title'   => 'XP-Systems Network',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'xpsystems.eu'],
                ['domain' => 'xpsystems.de'],
                ['domain' => 'xpsys.de'],
                ['domain' => 'xp-mail.eu'],
                ['domain' => 'xp-ad.de'],
                ['domain' => 'ptero01.eu'],
                ['domain' => 'epyc01.eu'],
                ['domain' => 'ryzen01.eu'],
            ],
        ],
        [
            'title'   => 'EuropeHost Network',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'europehost.eu'],
                ['domain' => 'eudomains.eu'],
                ['domain' => '24mc.eu'],
                ['domain' => 'mchost24.eu'],
                ['domain' => 'nerax.eu'],
                ['domain' => 'swiftshare.eu'],
                ['domain' => 'eushare.eu'],
                ['domain' => 'domaingen.de'],
                ['domain' => 'dsc.pics',      'badge' => 'GitHub'],
                ['domain' => 'twch.pics'],
                ['domain' => 'mcserver.lol'],
            ],
        ],
        [
            'title'   => 'MTEX.dev & Projects',
            'accent'  => 'partner',
            'domains' => [
                ['domain' => 'mtex.dev',       'badge' => 'GitHub'],
                ['domain' => 'api-sandbox.de', 'badge' => 'GitHub'],
                ['domain' => 'sandbox-api.de'],
                ['domain' => 'gimy.site',      'badge' => 'GitHub'],
                ['domain' => 'getmy.blog'],
                ['domain' => 'getmy.name'],
                ['domain' => 'urlk.app'],
                ['domain' => 'yourlink.app'],
                ['domain' => 'csslib.eu'],
                ['domain' => 'anlink.eu'],
            ],
        ],
        [
            'title'   => 'Official & Protection',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'bank-of-germany.de'],
                ['domain' => 'schulchat-rlp.de'],
                ['domain' => 'schulkampus-rlp.de'],
                ['domain' => 'bildungslogin-rlp.de'],
                ['domain' => 'bildungsbereich-rlp.de'],
                ['domain' => 'hhg-kl.eu'],
                ['domain' => 'staatliches-heinrich-heine-gymnasium-kaiserslautern.de'],
            ],
        ],
        [
            'title'   => 'Other Active Domains',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'kaufenhof.de',                        'badge' => 'Client'],
                ['domain' => 'heimatverein-floersheim-dalsheim.de'],
                ['domain' => 'woistdasdrachenei.de'],
                ['domain' => 'pythonhub.eu'],
                ['domain' => 'xmage.eu'],
                ['domain' => 'imagu.eu'],
                ['domain' => 'pyshop.de'],
                ['domain' => '2note.eu'],
                ['domain' => 'burgermc.de'],
                ['domain' => 'laravel-tutorial.eu'],
                ['domain' => 'spielefrei.de'],
                ['domain' => 'xpgames.eu'],
                ['domain' => '192-168-0-1.de'],
            ],
        ],
        [
            'title'   => 'Legacy (Expired)',
            'accent'  => 'accent',
            'legacy'  => true,
            'domains' => [
                ['domain' => 'xp-craft.de'],
                ['domain' => 'darkangel-mc.de'],
                ['domain' => 'XP-Host.de'],
                ['domain' => 'ebay-konto.de'],
                ['domain' => 'CityCraft-NW.de'],
                ['domain' => 'mail-free.de'],
                ['domain' => 'michaelninder.de'],
                ['domain' => 'XP-Link.de'],
                ['domain' => 'DogWaterDev.de'],
                ['domain' => 'XP-Node.de'],
                ['domain' => 'Dexify.eu'],
                ['domain' => 'XP-Cloud.eu'],
                ['domain' => 'Code-Trainer.de'],
                ['domain' => 'A-Sub.de'],
                ['domain' => 'B-Sub.de'],
                ['domain' => 'HHGkl.de'],
                ['domain' => 'CityCraft-SMP.de'],
                ['domain' => 'QuizHive.de'],
                ['domain' => 'Bank-of-Europe.eu'],
                ['domain' => 'CraftAttack.xyz'],
                ['domain' => 'EuroMC.eu'],
                ['domain' => 'XP-H.de'],
                ['domain' => 'XP-L.de'],
                ['domain' => 'Sub2.eu'],
                ['domain' => 'WebStruct.eu'],
                ['domain' => 'McServerTools.eu'],
                ['domain' => 'XPHost.eu'],
                ['domain' => 'MCPractice.eu'],
                ['domain' => 'NovaStack.eu'],
                ['domain' => 'FlexiStack.eu'],
                ['domain' => 'PelicanHost.eu'],
                ['domain' => 'axiohost.eu'],
                ['domain' => 'axiohost.de'],
                ['domain' => 'city-craft.de'],
                ['domain' => 'XP-Domains.de'],
                ['domain' => 'XP-Domain.de'],
                ['domain' => 'xfolio.eu'],
                ['domain' => 'eupractice.eu'],
                ['domain' => 'soulnode.eu'],
            ],
        ],
    ],
];